spring:
    profiles:
      active: localhost
    application:
        name: ace-schedule-wo

# 配置swagger
swagger:
    enabled: true
    base-package: com.github.wxiaoqi.security.schedulewo
    title: ace-schedule-wo
    version: 1.0.0.SNAPSHOT
    description: 工单服务
    contact:
        name: admin

logging:
  level:
    #        tk.mybatis: DEBUG
    com.github.wxiaoqi.security.schedulewo: DEBUG
  file: /mnt/logs/ace-schedulewo.log
  file.max-size: 10MB
  file.max-history : 365
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] %X{logthreadId} %-5level %logger{80} %line - %msg%n'
    console: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] %X{logthreadId} %-5level %logger{80} %line - %msg%n'



