spring:
    profiles:
      active: localhost
    application:
      name: ace-auth

# 配置swagger
swagger:
    enabled: true
    base-package: com.github.wxiaoqi.security.auth
    title: ace-auth
    version: 1.0.0.SNAPSHOT
    description: 鉴权服务
    contact:
        name: auth

logging:
  level:
    #        tk.mybatis: DEBUG
    com.github.wxiaoqi.security.auth: DEBUG
  file: /mnt/logs/ace-auth-server.log
  file.max-size: 10MB
  file.max-history : 365
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] %X{logthreadId} %-5level %logger{80} %line - %msg%n'
    console: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] %X{logthreadId} %-5level %logger{80} %line - %msg%n'